<?php
/**
 * Created by PhpStorm.
 * User: crazer
 * Date: 01.11.2018
 * Time: 22:15
 */

namespace app\components;


use yii\base\Widget;
use Yii;

class TotalWidget extends Widget
{
    public $tpl;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub

        $user_id=1;
        $total_arr = Yii::$app->db->createCommand('
SELECT SUM(total) AS total,deposit_id, name, images, position FROM 
          (
          SELECT SUM(total) AS total, deposit AS deposit_id, d.name, d.images, d.position FROM 
                  (SELECT -1*SUM(amount) AS total, deposit_from AS deposit FROM exchange WHERE user_id='.$user_id.' GROUP BY deposit
                  UNION
                  SELECT SUM(amount) AS total, deposit_to AS deposit FROM exchange WHERE user_id='.$user_id.' GROUP BY deposit) AS a 
                  JOIN deposits d ON a.deposit=d.id GROUP by deposit_id
          UNION
          SELECT total, dep.id AS deposit_id, dep.name, dep.images, dep.position FROM deposits dep 
          JOIN 
          (SELECT SUM(amount) AS total, deposit_id FROM operations WHERE user_id='.$user_id.' GROUP by deposit_id) AS dd 
          ON dd.deposit_id=dep.id) as a GROUP by deposit_id, name')->queryAll();
        print_r($total_arr);
    }
}